=== jimcoles/java-lib/src/main/java/resources/FlexModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!--
    XSD Help (http://www.w3.org/TR/xmlschema-1/#cIdentity-constraint_Definitions):

            <xs:unique name="port" >
              <xs:selector xpath="wsdl:port" />
              <xs:field xpath="@name" />
            </xs:unique>

        <xs:key name="portType" >
          <xs:selector xpath="wsdl:portType" />
          <xs:field xpath="@name" />
        </xs:key>

    <unique
      id = ID
      name = NCName
      {any attributes with non-schema namespace . . .}>
      Content: (annotation?, (selector, field+))
    </unique>

    <key
      id = ID
      name = NCName
      {any attributes with non-schema namespace . . .}>
      Content: (annotation?, (selector, field+))
    </key>

    <keyref
      id = ID
      name = NCName
      refer = QName
      {any attributes with non-schema namespace . . .}>
      Content: (annotation?, (selector, field+))
    </keyref>

    <selector
      id = ID
      xpath = a subset of XPath expression, see below
      {any attributes with non-schema namespace . . .}>
      Content: (annotation?)
    </selector>

    <field
      id = ID
      xpath = a subset of XPath expression, see below
      {any attributes with non-schema namespace . . .}>
      Content: (annotation?)
    </field>


     -->
    <!--
        <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude"></xsd:import>
     -->

    <xsd:element name="FlexModel">
        <xsd:annotation>
            <xsd:documentation>
                Top-level element containing model elements such as
                EntityType.
            </xsd:documentation>
        </xsd:annotation>

        <xsd:complexType>
            <xsd:sequence>
                <xsd:group ref="ModelElementGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Specify all 'KEYS', both 'Primary' and 'Foreign' here. -->


        <!-- Keys for Element: PrimitiveType -->

        <xsd:key name="PrimitiveType_PK">
            <xsd:selector xpath="./PrimitiveType"/>
            <xsd:field xpath="codeName"/>
        </xsd:key>

        <!-- Keys for Element: RelationshipType -->

        <xsd:key name="RelationshipType_PK">
            <xsd:selector xpath="./RelationshipType"/>
            <xsd:field xpath="codeName"/>
        </xsd:key>


        <!-- Keys for Element: EntityType -->

        <xsd:key name="EntityType_PK">
            <xsd:selector xpath="./EntityType"/>
            <xsd:field xpath="codeName"/>
        </xsd:key>

        <!-- Keys for Element: Attribute -->

        <xsd:key name="Attribute_PK">
            <xsd:selector xpath="./Attribute"/>
            <xsd:field xpath="parentEntityTypeName"/>
            <xsd:field xpath="codeName"/>
        </xsd:key>

        <xsd:keyref name="Attribute_to_PrimitiveType_FK" refer="PrimitiveType_PK">
            <xsd:selector xpath="./Attribute"/>
            <xsd:field xpath="dataTypeName"/>
        </xsd:keyref>

        <xsd:keyref name="Attribute_to_EntityType_FK" refer="EntityType_PK">
            <xsd:selector xpath="./Attribute"/>
            <xsd:field xpath="parentEntityTypeName"/>
        </xsd:keyref>

        <xsd:keyref name="Attribute_to_ReferencedEntityType_FK" refer="EntityType_PK">
            <xsd:selector xpath="./Attribute"/>
            <xsd:field xpath="toEntityTypeName"/>
        </xsd:keyref>

        <!-- Keys for Element: TypeRelationship -->

        <xsd:key name="TypeRelationship_PK">
            <xsd:selector xpath="./TypeRelationship"/>
            <xsd:field xpath="fromEntityTypeName"/>
            <xsd:field xpath="codeName"/>
        </xsd:key>

        <xsd:keyref name="TypeRelationship_to_RelationshipType_FK" refer="RelationshipType_PK">
            <xsd:selector xpath="./TypeRelationship"/>
            <xsd:field xpath="relationshipTypeName"/>
        </xsd:keyref>

        <xsd:keyref name="TypeRelationship_to_FromEntityType_FK" refer="EntityType_PK">
            <xsd:selector xpath="./TypeRelationship"/>
            <xsd:field xpath="fromEntityTypeName"/>
        </xsd:keyref>

        <xsd:keyref name="TypeRelationship_to_ToEntityType_FK" refer="EntityType_PK">
            <xsd:selector xpath="./TypeRelationship"/>
            <xsd:field xpath="toEntityTypeName"/>
        </xsd:keyref>

    </xsd:element>

    <xsd:group name="ModelElementGroup">
        <xsd:choice>
            <xsd:element ref="RelationshipType"></xsd:element>
            <xsd:element ref="PrimitiveType"></xsd:element>
            <xsd:element ref="ProcessNodeType"></xsd:element>
            <xsd:element ref="EntityType"></xsd:element>
            <xsd:element ref="Attribute"></xsd:element>
            <xsd:element ref="TypeRelationship"></xsd:element>
            <xsd:element ref="Procedure"></xsd:element>
            <xsd:element ref="BusinessProcess"></xsd:element>
            <xsd:element ref="ProcessNode"></xsd:element>
            <xsd:element ref="NodeConstraint"></xsd:element>
        </xsd:choice>
    </xsd:group>

    <!-- **********************************************************************
        Start of semi-auto-generated XSD declarations.
    ************************************************************************ -->

    <!--
      Generated by Velocity template.
      RDB Table: BC_ATTRIBUTE
      XML Element name/Java class name: Attribute
    -->
    <xsd:element name="Attribute">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: Attribute
                Description: Maps to java class of the same name (Attribute) and
                RDB table BC_ATTRIBUTE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all minOccurs="0" maxOccurs="1">
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="length" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="parentEntityTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="parentEntityTypeName" type="xsd:string"/>
                <xsd:element name="dataTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="dataTypeName" type="xsd:string"/>
                <xsd:element name="toEntityTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="toEntityTypeName" type="xsd:string" minOccurs="0"/>
            </xsd:all>
        </xsd:complexType>

    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_BUSINESS_PROCESS
      XML Element name/Java class name: BusinessProcess
    -->
    <xsd:element name="BusinessProcess">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: BusinessProcess
                Description: Maps to java class of the same name (BusinessProcess) and
                RDB table BC_BUSINESS_PROCESS
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="processEntityTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="processEntityTypeName" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_CONSTRAINT_TYPE
      XML Element name/Java class name: ConstraintType
    -->
    <xsd:element name="ConstraintType">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: ConstraintType
                Description: Maps to java class of the same name (ConstraintType) and
                RDB table BC_CONSTRAINT_TYPE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_ENTITY_TYPE
      XML Element name/Java class name: EntityType
    -->
    <xsd:element name="EntityType">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: EntityType
                Description: Maps to java class of the same name (EntityType) and
                RDB table BC_ENTITY_TYPE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="serviceGroupOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="isEnumerated" type="xsd:long" minOccurs="0"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_NODE_CONSTRAINT
      XML Element name/Java class name: NodeConstraint
    -->
    <xsd:element name="NodeConstraint">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: NodeConstraint
                Description: Maps to java class of the same name (NodeConstraint) and
                RDB table BC_NODE_CONSTRAINT
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="fromNodeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="fromNodeName" type="xsd:string"/>
                <xsd:element name="constraintTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="constraintTypeName" type="xsd:string"/>
                <xsd:element name="toNodeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="toNodeName" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_PRIMITIVE_TYPE
      XML Element name/Java class name: PrimitiveType
    -->
    <xsd:element name="PrimitiveType">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: PrimitiveType
                Description: Maps to java class of the same name (PrimitiveType) and
                RDB table BC_PRIMITIVE_TYPE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_PROCEDURE
      XML Element name/Java class name: Procedure
    -->
    <xsd:element name="Procedure">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: Procedure
                Description: Maps to java class of the same name (Procedure) and
                RDB table BC_PROCEDURE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_PROCESS_NODE
      XML Element name/Java class name: ProcessNode
    -->
    <xsd:element name="ProcessNode">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: ProcessNode
                Description: Maps to java class of the same name (ProcessNode) and
                RDB table BC_PROCESS_NODE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="processOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="processName" type="xsd:string"/>
                <xsd:element name="subProcessOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="subProcessName" type="xsd:string" minOccurs="0"/>
                <xsd:element name="nodeTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="nodeTypeName" type="xsd:string"/>
                <xsd:element name="displayName" type="xsd:string"/>
                <xsd:element name="isStartNode" type="xsd:long"/>
                <xsd:element name="serviceGroupOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="serviceGroupName" type="xsd:string"/>
                <xsd:element name="defaultAssigneeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="defaultAssigneeName" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_PROCESS_NODE_TYPE
      XML Element name/Java class name: ProcessNodeType
    -->
    <xsd:element name="ProcessNodeType">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: ProcessNodeType
                Description: Maps to java class of the same name (ProcessNodeType) and
                RDB table BC_PROCESS_NODE_TYPE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_RELATIONSHIP_TYPE
      XML Element name/Java class name: RelationshipType
    -->
    <xsd:element name="RelationshipType">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: RelationshipType
                Description: Maps to java class of the same name (RelationshipType) and
                RDB table BC_RELATIONSHIP_TYPE
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!--
      Generated by Velocity template.
      RDB Table: BC_TYPE_RELATIONSHIP
      XML Element name/Java class name: TypeRelationship
    -->
    <xsd:element name="TypeRelationship">
        <xsd:annotation>
            <xsd:documentation>
                XML Element: TypeRelationship
                Description: Maps to java class of the same name (TypeRelationship) and
                RDB table BC_TYPE_RELATIONSHIP
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="oid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="codeName" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="fromEntityTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="fromEntityTypeName" type="xsd:string"/>
                <xsd:element name="toEntityTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="toEntityTypeName" type="xsd:string"/>
                <xsd:element name="relationshipTypeOid" type="xsd:long" minOccurs="0"/>
                <xsd:element name="relationshipTypeName" type="xsd:string"/>
                <xsd:element name="requiredFlag" type="xsd:long" minOccurs="0"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>


</xsd:schema>

=== jimcoles/java-lib/src/main/java/resources/BasecampFlexModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<FlexModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="FlexModel.xsd">

    <!--Start Relationship Types-->

    <RelationshipType>
        <codeName>extends</codeName>
        <description>OO Extension</description>
    </RelationshipType>
    <RelationshipType>
        <codeName>references</codeName>
        <description>Like an RDB FK</description>
    </RelationshipType>

    <!--Start Primitive (data) Types-->

    <PrimitiveType>
        <codeName>long</codeName>
        <description>Long integer</description>
    </PrimitiveType>
    <PrimitiveType>
        <codeName>string</codeName>
        <description>Character String</description>
    </PrimitiveType>

    <PrimitiveType>
        <codeName>date</codeName>
        <description>A date or timestamp</description>
    </PrimitiveType>

    <!--
      Very Base EntityType's
    -->

    <EntityType>
        <codeName>FlexEntity</codeName>
        <description>Base class of all types including BusinessEntity and MetaEntity</description>
    </EntityType>
    <Attribute>
        <codeName>oid</codeName>
        <description>System identifier</description>
        <length>0</length>
        <parentEntityTypeName>FlexEntity</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
    </Attribute>

    <EntityType>
        <codeName>BusinessEntity</codeName>
        <description>Base Business Entity Types such as a GeneralWorkRequest</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>

    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-like extension</description>
        <requiredFlag>0</requiredFlag>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>BusinessEntity</fromEntityTypeName>
        <toEntityTypeName>FlexEntity</toEntityTypeName>
    </TypeRelationship>

    <EntityType>
        <codeName>MetaEntity</codeName>
        <description>Base Meta Entity Types such as a GeneralWorkRequest</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>

    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-like extension</description>
        <requiredFlag>0</requiredFlag>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>MetaEntity</fromEntityTypeName>
        <toEntityTypeName>FlexEntity</toEntityTypeName>
    </TypeRelationship>

    <EntityType>
        <codeName>EntityType</codeName>
        <description>Entity Type</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>
    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-like extension</description>
        <requiredFlag>0</requiredFlag>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>EntityType</fromEntityTypeName>
        <toEntityTypeName>MetaEntity</toEntityTypeName>
    </TypeRelationship>

    <EntityType>
        <codeName>ProcessNode</codeName>
        <description>Process Node</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>
    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-like extension</description>
        <requiredFlag>0</requiredFlag>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>ProcessNode</fromEntityTypeName>
        <toEntityTypeName>MetaEntity</toEntityTypeName>
    </TypeRelationship>

    <!--Start core domain entity types-->

    <!--
      Generated by Velocity template.
      RDB Table: BC_WORK_REQUEST
      XML Element name/Java class name: WorkRequest
    -->
    <EntityType>
        <codeName>WorkRequest</codeName>
        <description>(enter desc here)</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>
    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-like extension</description>
        <requiredFlag>0</requiredFlag>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>WorkRequest</fromEntityTypeName>
        <toEntityTypeName>BusinessEntity</toEntityTypeName>
    </TypeRelationship>
    <Attribute>
        <codeName>oid</codeName>
        <description>(enter desc here)</description>
        <length>0</length>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>string</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>creationDate</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>date</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>lastUpdatedDate</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>date</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>entityTypeOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>needByDate</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>date</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>creatorPersonOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>requestorPersonOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>urgencyOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>WorkRequestUrgency</toEntityTypeName>
    </Attribute>
    <Attribute>
        <length>0</length>
        <codeName>requestorCc</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>string</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>statusOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>ProcessNode</toEntityTypeName>
    </Attribute>
    <Attribute>
        <codeName>requestMotiveOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeOid>1</parentEntityTypeOid>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>WorkRequestMotive</toEntityTypeName>
    </Attribute>
    <Attribute>
        <length>0</length>
        <codeName>resolution</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>WorkRequest</parentEntityTypeName>
        <dataTypeName>string</dataTypeName>
    </Attribute>

    <!--
      Generated by Velocity template.
      RDB Table: BC_GENERAL_WORK_REQUEST
      XML Element name/Java class name: GeneralWorkRequest
    -->
    <EntityType>
        <codeName>GeneralWorkRequest</codeName>
        <description>(enter desc here)</description>
        <serviceGroupOid>0</serviceGroupOid>
    </EntityType>
    <TypeRelationship>
        <codeName>extends</codeName>
        <description>OO-extension</description>
        <relationshipTypeName>extends</relationshipTypeName>
        <fromEntityTypeName>GeneralWorkRequest</fromEntityTypeName>
        <toEntityTypeName>WorkRequest</toEntityTypeName>
    </TypeRelationship>
    <Attribute>
        <length>0</length>
        <codeName>summary</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
        <dataTypeName>string</dataTypeName>
    </Attribute>
    <Attribute>
        <length>0</length>
        <codeName>description</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
        <dataTypeName>string</dataTypeName>
    </Attribute>
    <Attribute>
        <codeName>serviceableItemOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>ServiceableItem</toEntityTypeName>
    </Attribute>
    <Attribute>
        <codeName>serviceableItemTypeOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>ServiceableItem</toEntityTypeName>
    </Attribute>
    <Attribute>
        <codeName>businessImpactOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
        <dataTypeName>long</dataTypeName>
        <toEntityTypeName>EntityType</toEntityTypeName>
    </Attribute>
    <Attribute>
        <codeName>assignedToOid</codeName>
        <description>(enter desc here)</description>
        <parentEntityTypeName>GeneralWorkRequest</parentEntityTypeName>
